{
 "title": "Cassandra - Overview",
 "tags": [
  "tlp",
  "cassandra"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(org_apache_cassandra_metrics_Storage_Load, environment)"
   },
   {
    "name": "dc",
    "label": "Data Center",
    "query": "label_values(org_apache_cassandra_metrics_Storage_Load, data_center)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(org_apache_cassandra_metrics_Storage_Load, host)"
   }
  ]
 },
 "panels": [
  { "title": "Operational Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "dc" },
  {
   "title": "Read latencies (by data center)",
   "type": "graph",
   "description": "Monitor `p75` latencies to get a view of the cluster's typical operating latencies.\n\nMonitor the `p95` and `p99` latencies for anomalies to get an early indicator for potential issues.\n\n##### Required Actions\n\nIf `p95` read latency metrics spike, investigate:\n\n* Disk contention.\n* Frequent garbage collections.\n* Prolonged garbage collection times.\n* Inefficient read patterns.\n* Back pressure.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "µs", "label": "Read latency" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope=\"Read\", unit=\"75thPercentile\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{scope}}.Latency.p75",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Read.Latency.75percentile, 3), 2, 8, 9, 10)"
    },
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope=\"Read\", unit=\"95thPercentile\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{scope}}.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Read.Latency.95percentile, 3), 2, 8, 9, 10)"
    },
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope=\"Read\", unit=\"99thPercentile\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{scope}}.Latency.p99",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Read.Latency.99percentile, 3), 2, 8, 9, 10)"
    }
   ]
  },
  {
   "title": "Write latencies (by data center)",
   "type": "graph",
   "description": "Monitor `p75` latencies to get a view of the cluster's typical operating latencies.\n\nMonitor the `p95` and `p99` latencies for anomalies to get an early indicator for potential issues.\n\n##### Required Actions\n\nIf `p95` write latency metrics spike, investigate:\n\n* Disk contention.\n* Counter usage.\n* Lightweight transaction usage.\n* Frequent garbage collections.\n* Prolonged garbage collection times.\n* Back pressure.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "µs", "label": "Write latency" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope=\"Write\", unit=\"75thPercentile\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{scope}}.Latency.p75",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Write.Latency.75percentile, 3), 2, 8, 9, 10)"
    },
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope=\"Write\", unit=\"95thPercentile\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{scope}}.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Write.Latency.95percentile, 3), 2, 8, 9, 10)"
    },
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope=\"Write\", unit=\"99thPercentile\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{scope}}.Latency.p99",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Write.Latency.99percentile, 3), 2, 8, 9, 10)"
    }
   ]
  },
  {
   "title": "Other operations latencies (by data center)",
   "type": "graph",
   "description": "Monitor the `p95` and `p99` latencies for anomalies to get an early indicator for potential issues.\n\n##### Required Actions\n\nIf experiencing issues with this graph, use the additional TLP graphs to detect issues with the specific request type that triggered the alert.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "µs", "label": "Operational latencies" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope!=\"Write\", scope!=\"Read\", unit=\"95thPercentile\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{host}}.{{scope}}.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.{CASRead,CASWrite,RangeSlice}.Latency.95percentile, 3), 2, 8, 9, 10)"
    }
   ]
  },
  { "title": "Operation Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "dc" },
  {
   "title": "Read request counts (by data center)",
   "type": "graph",
   "description": "Display the number of read requests by data center.\n\n##### Values\n\nChanges in this graph should match closely with application load.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "opm", "label": "Read counts" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope=\"Read\", unit=\"OneMinuteRate\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{scope}}.Requests.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Read.Latency.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  {
   "title": "Write request counts (by data center)",
   "type": "graph",
   "description": "Display the number of write requests by data center.\n\n##### Values\n\nChanges in this graph should match closely with application load.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "opm", "label": "Write counts" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope=\"Write\", unit=\"OneMinuteRate\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{scope}}.Requests.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Write.Latency.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  {
   "title": "Other request counts (by data center)",
   "type": "graph",
   "description": "Display the number of other requests by data center.\n\n##### Values\n\nChanges in this graph should match closely with application load.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "opm", "label": "Other counts" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{environment=\"$env\", data_center=\"$dc\", scope!=\"Read\", scope!=\"Write\", unit=\"OneMinuteRate\"}) by (environment, data_center, scope)",
     "legendFormat": "{{environment}}.{{data_center}}.{{host}}.{{scope}}.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.{CASRead,CASWrite,RangeSlice}.Latency.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  { "title": "Other Important Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "dc" },
  {
   "title": "Dropped messages (by data center)",
   "type": "graph",
   "description": "Display the number of dropped messages per request type, by data center.\n\n##### Values\n\nA ideal value of `0` means that no requests have been dropped.\n\n##### Required Actions\n\nValues higher than `0` indicates an under-provisioned cluster for the specific request types. Under-provisioned clusters often times will experience the following issues that cause dropped messages:\n\n* Frequent garbage collections.\n* Prolonged garbage collection times.\n* Inefficient read patterns.\n* Back pressure.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "opm", "label": "Dropped messages" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_DroppedMessages_Dropped{environment=\"$env\", data_center=\"$dc\"}) by (environment, data_center, message_type)",
     "legendFormat": "{{environment}}.{{data_center}}.{{message_type}}",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.DroppedMessage.*.Dropped.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  {
   "title": "Max partition size (by node and table)",
   "type": "table",
   "description": "This graph displays the `max` size of a partition across all nodes and tables.\n\n##### Values\n\nThe max size of the row must be taken into account when calculating the amount of required heap space.\n\nWhile the maximum number of partition cells (CQL rows x CQL columns) is limited to 2 billion and a single column value is restricted to 2GB, the real-world limitation exists at around 100MB partitions.\n\nOnce partitions grow to more than 100MB:\n\n* Row caching can quickly be busted as a single row can consume all of the allocated row cache heap space.\n* Out of Memory exceptions may occur frequently as a single row may take over the majority of the heap space.\n* CPU and disk load may increase as multiple passes may be needed to load a row into memory.\n* Compactions may cause heap pressure as rows are read into memory before being written to the new SSTables.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "max(org_apache_cassandra_metrics_Table_MaxRowSize{environment=\"$env\", data_center=\"$dc\"}) by (environment, data_center, host, keyspace, table)",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.*.*.MaxRowSize.value, 2, 3, 9, 10)"
    }
   ]
  },
  {
   "title": "Pending Compactions (by host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Table_PendingCompactions{environment=\"$env\", data_center=\"$dc\"}) by (environment, data_center, host)",
     "legendFormat": "{{environment}}.{{data_center}}.{{host}}.PendingCompactions",
     "target": "cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.all.PendingCompactions.value"
    }
   ]
  },
  { "title": "JVM ParNew CMS GC Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "JVM ParNew runs",
   "type": "graph",
   "description": "@Alex/@Alain, why `.runs`, instead `.time`?",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms", "label": "Garbage collection times" }
   ],
   "targets": [
    {
     "expr": "deriv(jvm_gc_ParNew{environment=\"$env\", data_center=\"$dc\", unit=\"CollectionTime\"}[1m])",
     "legendFormat": "{{environment}}.{{data_center}}.{{host}}.ParNew.{{unit}}",
     "target": "derivative(cassandra.$env.$dc.$host.jvm.gc.ParNew.runs)"
    }
   ]
  }
 ]
}