version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      metrics-processor-net:
        ipv4_address: 172.21.0.2
  kafka:
    image: confluentinc/cp-kafka:5.4.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 7071:7071
    volumes:
      - ../kafka/config/prometheus.yml:/prometheus/prometheus.yml
      - ../jmx_exporter/lib/jmx_prometheus_javaagent-0.12.0.jar:/prometheus/jmx_prometheus_javaagent-0.12.0.jar
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.21.0.3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: -javaagent:/prometheus/jmx_prometheus_javaagent-0.12.0.jar=7071:/prometheus/prometheus.yml
    networks:
      metrics-processor-net:
        ipv4_address: 172.21.0.3
  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    depends_on:
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: 172.21.0.4
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_DEBUG: "true"
    networks:
      metrics-processor-net:
        ipv4_address: 172.21.0.4
  cassandra:
    build:
      cassandra
    volumes:
      - ../cassandra/src/main/resources/cassandra:/opt/metrics-processor/cassandra
      - ../cassandra/config/prometheus.yml:/prometheus/prometheus.yml
      - ./data/cassandra:/var/lib/cassandra
      - ../jmx_exporter/lib/jmx_prometheus_javaagent-0.12.0.jar:/prometheus/jmx_prometheus_javaagent-0.12.0.jar
    ports:
      - 9042:9042
      - 7199:7199
      - 7070:7070
    networks:
      metrics-processor-net:
        ipv4_address: 172.21.0.5
  grafana:
    image: grafana/grafana:6.6.2
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      metrics-processor-net:
        ipv4_address: 172.21.0.6
  prometheus:
    build:
      prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/prometheus
      - ../prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      metrics-processor-net:
        ipv4_address: 172.21.0.7
networks:
  metrics-processor-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.21.0.0/16
          gateway: 172.21.0.1